#Tomcat
server:
  port: 9000

spring:
  application:
    # 应用名称
    name: shop-user-server

  cloud:
    nacos:
      # 服务发现
      discovery:
        server-addr: 192.168.222.128:8848
        #用于分组 测试
        group: djx-mall
        #dev 的id
        namespace: 59e99910-5091-4a9b-bc3b-b3a44fdaf2bd
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      # 初始化大小
      initial-size: 5
      # 最小连接数
      min-idle: 30
      # 最大连接数
      max-active: 10000
      # 获取连接时的最大等待时间
      max-wait: 60000
      # 一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 多久才进行一次检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
        # 配置扩展插件：stat-监控统计，log4j-日志，wall-防火墙（防止SQL注入），去掉后，监控界面的sql无法统计
      filters: stat,wall
        # 检测连接是否有效的 SQL语句，为空时以下三个配置均无效
      validation-query: SELECT 1
        # 申请连接时执行validationQuery检测连接是否有效，默认true，开启后会降低性能
      test-on-borrow: false
        # 归还连接时执行validationQuery检测连接是否有效，默认false，开启后会降低性能
      test-on-return: false
        # 申请连接时如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效，默认false，建议开启，不影响性能
      test-while-idle: false
      # 访问UI界面 http://127.0.0.1:9000/druid/index.html
      stat-view-servlet:
          # 是否开启 StatViewServlet
          enabled: true
          # 访问监控页面 白名单，默认127.0.0.1
          allow: 127.0.0.1
          # 访问监控页面 黑名单
          deny: 192.168.56.1
          # 访问监控页面 登陆账号
          login-username: admin
          # 访问监控页面 登陆密码
          login-password: admin
      filter:
        stat:
          enabled: true                                     # 是否开启 FilterStat，默认true
          log-slow-sql: false                                # 是否开启 慢SQL 记录，默认false
          slow-sql-millis: 5000                             # 慢 SQL 的标准，默认 3000，单位：毫秒
          merge-sql: false                                  # 合并多个连接池的监控数据，默认false

  #配置redis
  redis:
    host: 192.168.222.128
    port: 6379
    lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 100
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 5000ms
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 1
    timeout: PT10S
    password: 123456
#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
